name: attendance_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  clipboard: ^0.1.3
  intl: ^0.17.0
  google_fonts: ^3.0.1
  screenshot: ^1.2.3
  share: ^2.0.4
  path_provider: ^2.0.11
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lint: ^1.0.0
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
