name: attendance_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter


  shared_preferences: ^2.0.15
  provider: ^6.0.3
  clipboard: ^0.1.3
  intl: ^0.17.0
  google_fonts: ^3.0.1
  screenshot: ^1.2.3
  share: ^2.0.4
  path_provider: ^2.0.11
  hive: ^2.2.3
  lottie: ^1.4.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/
