import 'dart:io';
import 'dart:typed_data';

import 'package:clipboard/clipboard.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'package:screenshot/screenshot.dart';
import 'package:share/share.dart';

import '../providers/students_list_provider.dart';

class Utils {
  Utils._();

  static String getCopyableTextAndCopy(
    BuildContext context, {
    required String username,
    required String header,
    required String date,
    required String report,
  }) {
    String textToBeCopied = '';
    textToBeCopied += '$header\n$date\n';
    textToBeCopied += Provider.of<StudentListProvider>(context, listen: false)
            .ifGetAbsenteesList
        ? 'LIST OF ABSENT STUDENTS\n'
        : 'LIST OF PRESENT STUDENTS\n';

    textToBeCopied += report;
    textToBeCopied += '\n\n---------------------\n';
    textToBeCopied +=
        '\nReport Generated by $username using MUET CRs Companion App';

    FlutterClipboard.copy(textToBeCopied).then(
      (value) => ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
            'Text Copied to clipboard!',
            style: TextStyle(fontSize: 17),
          ),
        ),
      ),
    );
    Share.share(textToBeCopied);
    return textToBeCopied;
  }

  static takeAndShareScreenshot(
    ScreenshotController screenshotController,
  ) async {
    await screenshotController
        .capture(delay: const Duration(milliseconds: 10))
        .then((Uint8List? image) async {
      if (image != null) {
        final directory = await getApplicationDocumentsDirectory();
        final imagePath = await File('${directory.path}/image.png').create();
        await imagePath.writeAsBytes(image);
        await Share.shareFiles([imagePath.path]);
      }
    });
  }
}
